# Вариант 1
Электрическая цепь состоит из $ n $ резисторов. В таблице приведены
сопротивления на каждом резисторе $ r $. Cила тока $ I $ в цепи, а следовательно и на каждом
резисторе равна 3.30 А

|   | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 |
|---|---|---|---|---|---|---|---|---|
| r, Ом | 0.7 | 0.6 | 1.0 | 0.7 | 1.1 | 1.5 | 1.6 | 1.2 |

Резисторы в цепи соединены последовательно.
Вычислить:
- напряжение $ u_i $ на каждом резисторе по формуле (сформировать вектор):
$$ u_i = I * r_i $$
- общее сопротивление цепи по формуле:
$$ R = r_{1} + r_{2} + ... + r_n $$
- напряжение в цепи по формуле:
$$ U = u_1 + u_2 + ... + u_n $$
- найти напряжение на концах новой цепи, в которую включены резисторы с
номерами с 1 по 5 (включительно), а сила тока в ней составляет 4.1 А


In [12]:
import numpy as np
import math

In [11]:
resistors = [0.7, 0.6, 1.0, 0.7, 1.1, 1.5, 1.6, 1.2]
u_resistors = []
for r in resistors:
    u_resistors.append(r * 3.30)
# формируем вектор
for r in u_resistors:
    i = 1
    print(f"Резистор № {i} = {r} В")
    i+=1

R_allresisrors = 0
U_allresistors = 0
for r in resistors:
    R_allresisrors += r
print(f"Общее сопротивление цепи = {R_allresisrors} Ом")

for u in u_resistors:
    U_allresistors += u
print(f"Общее напряжение в цепи = {U_allresistors} В")
# Для новой цепи:
R_all_in_new = 0
for r in resistors[:5]:
    R_all_in_new += r
U_in_new = R_all_in_new  * 4.1
print(f"Напряжение на конце цепи = {U_in_new}")

Резистор № 1 = 2.3099999999999996 В
Резистор № 1 = 1.9799999999999998 В
Резистор № 1 = 3.3 В
Резистор № 1 = 2.3099999999999996 В
Резистор № 1 = 3.63 В
Резистор № 1 = 4.949999999999999 В
Резистор № 1 = 5.28 В
Резистор № 1 = 3.9599999999999995 В
Общее сопротивление цепи = 8.399999999999999 Ом
Общее напряжение в цепи = 27.72 В
Напряжение на конце цепи = 16.81


Даны квадратная матрица A, размером N на N, и вектор B, размером N (N = 4),
элементы которых определены следующим образом:
$$𝑎_𝑖𝑗 = 𝑠𝑖𝑛 (\frac{\sqrt{2} \cdot 𝜋 \cdot 𝑗} {2} + 1) \cdot ln \sqrt{𝑖} + 2 , 𝑏𝑖 = sin (𝑖2 −\frac{𝜋}{\sqrt{2}})$$

Выполнить следующие действия:
- вычислить матричное выражение:
$$𝐴^3 \cdot 𝐵 + 5 \cdot 𝐴^−1 \cdot 𝐵$$
- вычислить сумму элементов матрицы A и сумму элементов вектора B;
- получить новый вектор C, каждый элемент которого определяется как:
$$ 𝑐𝑖 = 𝑏_𝑖 \cdot \underset{𝑗=0..𝑁−1}{max}    𝑎_{ij} $$
- найти скалярное произведение векторов B и C;
- вывести индексы всех максимальных элементов матрицы А.


In [17]:
N = 4


A = np.zeros((N, N))
for i in range(N):
    for j in range(N):
        a_ij = math.sin(math.sqrt(2) * math.pi * (j+1) / 2 + 1) * math.log(math.sqrt(i+1)) + 2
        A[i, j] = a_ij


B = np.zeros(N)
for i in range(N):
    b_i = math.sin((i+1)**2 - math.pi / math.sqrt(2))
    B[i] = b_i

#  Вычисление матричного выражения:
A_cubed = np.linalg.matrix_power(A, 3)
A_inv = np.linalg.inv(A)
result = np.dot(A_cubed, B) + 5 * np.dot(A_inv, B)
sum_A = np.sum(A)
sum_B = np.sum(B)

C = np.zeros(N)
for i in range(N):
    max_aij = np.max(A[i, :])
    C[i] = B[i] * max_aij


dot_product = np.dot(B, C)
max_value = np.max(A)
max_indices = np.argwhere(A == max_value)


print(f"Матрица A = \n{A}")

print(f"\nВектор B: \n{B}")

print(f"\nРезультат матричного выражения A³·B + 5·A⁻¹·B: {result}")
print(f"\nСумма элементов матрицы A:{sum_A}")
print(f"Сумма элементов вектора B:{sum_B}")
print(f"\nВектор C:{C}")
print(f"\nСкалярное произведение векторов B и C:{dot_product}")
print("\nИндексы максимальных элементов матрицы A (в 1-индексации):")
for index in max_indices:
    print(f"Строка {index[0]+1}, столбец {index[1]+1}")

Матрица A = 
[[2.         2.         2.         2.        ]
 [1.97235591 1.74185643 2.34035915 1.84583259]
 [1.95618515 1.59085212 2.53945649 1.75565044]
 [1.94471181 1.48371285 2.6807183  1.69166518]]

Вектор B: 
[-0.93959374  0.97849496  0.47536004  0.93638614]

Результат матричного выражения A³·B + 5·A⁻¹·B: [ 7.85865992e+15  1.34036492e+16  8.07552805e+14 -2.20698619e+16]

Сумма элементов матрицы A:31.54335641058755
Сумма элементов вектора B:1.4506474029006466

Вектор C:[-1.87918747  2.29002962  1.20715615  2.51018746]

Скалярное произведение векторов B и C:6.9307937472140555

Индексы максимальных элементов матрицы A (в 1-индексации):
Строка 4, столбец 3
